spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postsdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql

server:
  error:
    include-binding-errors: always
    include-message: always
